/**
 * Platform Admin Permissions & Role Matrices (Phase 7 Production Implementation)
 * Enforces least-privilege administrative access control.
 */

export const ADMIN_PERMISSIONS = {
  // Developer Management
  DEVELOPER_READ: 'DEVELOPER_READ',
  DEVELOPER_UPDATE: 'DEVELOPER_UPDATE',
  DEVELOPER_SUSPEND: 'DEVELOPER_SUSPEND',

  // Application Moderation & Lifecycle
  APP_READ: 'APP_READ',
  APP_REVIEW: 'APP_REVIEW',
  APP_APPROVE: 'APP_APPROVE',
  APP_REJECT: 'APP_REJECT',
  APP_BLOCK: 'APP_BLOCK',

  // Security Review Center
  SECURITY_READ: 'SECURITY_READ',
  SECURITY_REVIEW: 'SECURITY_REVIEW',
  SECURITY_APPROVE: 'SECURITY_APPROVE',

  // Payment & Commerce
  PAYMENT_READ: 'PAYMENT_READ',
  PAYMENT_VERIFY: 'PAYMENT_VERIFY',

  // Subscription Plans & Quotas
  SUBSCRIPTION_MANAGE: 'SUBSCRIPTION_MANAGE',

  // Support Ticketing
  SUPPORT_READ: 'SUPPORT_READ',
  SUPPORT_RESPOND: 'SUPPORT_RESPOND',

  // Community Reports
  REPORT_READ: 'REPORT_READ',
  REPORT_RESOLVE: 'REPORT_RESOLVE',

  // Immutable Audit Trail
  AUDIT_READ: 'AUDIT_READ',

  // Platform Configuration & Maintenance
  SETTINGS_READ: 'SETTINGS_READ',
  SETTINGS_UPDATE: 'SETTINGS_UPDATE',

  // Administration of Admins
  ADMIN_MANAGE: 'ADMIN_MANAGE',
};

export const ALL_PERMISSIONS = Object.values(ADMIN_PERMISSIONS);

/**
 * Standard Role-to-Permissions Mapping
 */
export const ROLE_PERMISSIONS_MAP = {
  SUPER_ADMIN: ALL_PERMISSIONS,

  ADMIN: [
    ADMIN_PERMISSIONS.DEVELOPER_READ,
    ADMIN_PERMISSIONS.DEVELOPER_UPDATE,
    ADMIN_PERMISSIONS.DEVELOPER_SUSPEND,
    ADMIN_PERMISSIONS.APP_READ,
    ADMIN_PERMISSIONS.APP_REVIEW,
    ADMIN_PERMISSIONS.APP_APPROVE,
    ADMIN_PERMISSIONS.APP_REJECT,
    ADMIN_PERMISSIONS.APP_BLOCK,
    ADMIN_PERMISSIONS.SECURITY_READ,
    ADMIN_PERMISSIONS.SECURITY_REVIEW,
    ADMIN_PERMISSIONS.SECURITY_APPROVE,
    ADMIN_PERMISSIONS.PAYMENT_READ,
    ADMIN_PERMISSIONS.PAYMENT_VERIFY,
    ADMIN_PERMISSIONS.SUBSCRIPTION_MANAGE,
    ADMIN_PERMISSIONS.SUPPORT_READ,
    ADMIN_PERMISSIONS.SUPPORT_RESPOND,
    ADMIN_PERMISSIONS.REPORT_READ,
    ADMIN_PERMISSIONS.REPORT_RESOLVE,
    ADMIN_PERMISSIONS.AUDIT_READ,
    ADMIN_PERMISSIONS.SETTINGS_READ,
    ADMIN_PERMISSIONS.SETTINGS_UPDATE,
  ],

  MODERATOR: [
    ADMIN_PERMISSIONS.APP_READ,
    ADMIN_PERMISSIONS.APP_REVIEW,
    ADMIN_PERMISSIONS.APP_APPROVE,
    ADMIN_PERMISSIONS.APP_REJECT,
    ADMIN_PERMISSIONS.APP_BLOCK,
    ADMIN_PERMISSIONS.REPORT_READ,
    ADMIN_PERMISSIONS.REPORT_RESOLVE,
    ADMIN_PERMISSIONS.DEVELOPER_READ,
    ADMIN_PERMISSIONS.AUDIT_READ,
  ],

  SECURITY_REVIEWER: [
    ADMIN_PERMISSIONS.SECURITY_READ,
    ADMIN_PERMISSIONS.SECURITY_REVIEW,
    ADMIN_PERMISSIONS.SECURITY_APPROVE,
    ADMIN_PERMISSIONS.APP_READ,
    ADMIN_PERMISSIONS.APP_REVIEW,
    ADMIN_PERMISSIONS.APP_BLOCK,
    ADMIN_PERMISSIONS.AUDIT_READ,
  ],

  SUPPORT_AGENT: [
    ADMIN_PERMISSIONS.SUPPORT_READ,
    ADMIN_PERMISSIONS.SUPPORT_RESPOND,
    ADMIN_PERMISSIONS.REPORT_READ,
    ADMIN_PERMISSIONS.REPORT_RESOLVE,
    ADMIN_PERMISSIONS.APP_READ,
    ADMIN_PERMISSIONS.DEVELOPER_READ,
  ],

  FINANCE_ADMIN: [
    ADMIN_PERMISSIONS.PAYMENT_READ,
    ADMIN_PERMISSIONS.PAYMENT_VERIFY,
    ADMIN_PERMISSIONS.SUBSCRIPTION_MANAGE,
    ADMIN_PERMISSIONS.DEVELOPER_READ,
    ADMIN_PERMISSIONS.AUDIT_READ,
    ADMIN_PERMISSIONS.SETTINGS_READ,
  ],
};

/**
 * Check if a given role is an administrative staff role
 * @param {string} role
 * @returns {boolean}
 */
export const isAdminRole = (role) => {
  return [
    'SUPER_ADMIN',
    'ADMIN',
    'MODERATOR',
    'SECURITY_REVIEWER',
    'SUPPORT_AGENT',
    'FINANCE_ADMIN',
  ].includes(role);
};

/**
 * Get all effective permissions for a user (combining role defaults + individual overrides)
 * @param {Object} user
 * @returns {string[]}
 */
export const getUserEffectivePermissions = (user) => {
  if (!user || !user.role) return [];
  if (user.role === 'SUPER_ADMIN') return ALL_PERMISSIONS;

  const rolePerms = ROLE_PERMISSIONS_MAP[user.role] || [];
  const customPerms = Array.isArray(user.permissions) ? user.permissions : [];

  return Array.from(new Set([...rolePerms, ...customPerms]));
};

export default {
  ADMIN_PERMISSIONS,
  ALL_PERMISSIONS,
  ROLE_PERMISSIONS_MAP,
  isAdminRole,
  getUserEffectivePermissions,
};
