/**
 * AppOrbit Mock Data Module
 * Dedicated fixtures for Phase 1 UI prototyping.
 * Note: Clearly decoupled from future API communication layers.
 */

export const mockApps = [
  {
    id: 'app-001',
    name: 'PulseGuard',
    slug: 'pulse-guard',
    icon: '❤️',
    shortDescription: 'AI-driven cardiac telemetry and real-time vital signs monitor.',
    description:
      'PulseGuard is an advanced health companion that pairs with wearable Bluetooth sensors to track arrhythmia, blood oxygen, and heart rate variability with clinical-grade accuracy.',
    version: '2.1.0',
    category: 'Health',
    developer: 'AuraHealth Labs',
    developerVerified: true,
    rating: 4.9,
    ratingCount: 1420,
    downloads: 48500,
    technologies: ['Kotlin', 'TensorFlow Lite', 'Bluetooth BLE', 'Room DB'],
    features: [
      'Continuous PPG waveform sensor telemetry',
      'Offline emergency detection algorithm',
      'Encrypted HL7/FHIR compliant medical export',
      'Low energy background sensor synchronization',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&auto=format&fit=crop&q=60',
    ],
    packageSize: '24.8 MB',
    minAndroid: 'Android 9.0 (API 28)',
    status: 'published',
    updatedAt: '2026-08-28T10:00:00.000Z',
    githubUrl: 'https://github.com/example/pulseguard',
    demoUrl: 'https://pulseguard.example.com',
  },
  {
    id: 'app-002',
    name: 'SmartWater',
    slug: 'smart-water',
    icon: '💧',
    shortDescription: 'Industrial and residential IoT flow telemetry and leak detection.',
    description:
      'SmartWater connects with smart flow meters and ultrasound acoustic sensors to monitor consumption patterns, detect silent underground leaks, and automate shutoff valves.',
    version: '1.4.2',
    category: 'Utilities',
    developer: 'AquaFlow Dynamics',
    developerVerified: true,
    rating: 4.7,
    ratingCount: 830,
    downloads: 21900,
    technologies: ['Flutter', 'MQTT', 'Node-RED', 'SQLite'],
    features: [
      'Micro-leak acoustic threshold monitoring',
      'Remote motorized shutoff valve triggering',
      'Tiered municipal billing consumption predictor',
      'Solar battery status and wireless signal heatmaps',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=60',
    ],
    packageSize: '18.4 MB',
    minAndroid: 'Android 8.0 (API 26)',
    status: 'published',
    updatedAt: '2026-08-15T14:30:00.000Z',
    githubUrl: 'https://github.com/example/smartwater',
    demoUrl: 'https://smartwater.example.com',
  },
  {
    id: 'app-003',
    name: 'School Saathi',
    slug: 'school-saathi',
    icon: '🎒',
    shortDescription: 'Integrated K-12 academic administration and hybrid classrooms.',
    description:
      'School Saathi bridges educators, students, and parents with real-time biometric attendance notifications, digital report cards, syllabus planners, and localized micro-learning modules.',
    version: '3.0.1',
    category: 'Education',
    developer: 'EduBharat Tech',
    developerVerified: true,
    rating: 4.8,
    ratingCount: 3600,
    downloads: 115000,
    technologies: ['Jetpack Compose', 'WebRTC', 'Firebase', 'Coroutines'],
    features: [
      'Multilingual parent-teacher encrypted messaging',
      'Offline video lecture caching and interactive quizzes',
      'GPS school bus location broadcasting',
      'Automated homework grading and progress analytics',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=60',
    ],
    packageSize: '32.1 MB',
    minAndroid: 'Android 7.0 (API 24)',
    status: 'published',
    updatedAt: '2026-09-01T08:15:00.000Z',
    githubUrl: 'https://github.com/example/schoolsaathi',
    demoUrl: 'https://schoolsaathi.example.com',
  },
  {
    id: 'app-004',
    name: 'HostelEase',
    slug: 'hostel-ease',
    icon: '🏢',
    shortDescription: 'Campus accommodation, mess meal management, and night curfew passes.',
    description:
      'HostelEase streamlines university residence operations with digital entry/exit QR gate passes, automated mess menu voting, maintenance complaint tickets, and roommate bill splitting.',
    version: '1.8.0',
    category: 'Productivity',
    developer: 'CampusOps Solutions',
    developerVerified: false,
    rating: 4.6,
    ratingCount: 940,
    downloads: 34200,
    technologies: ['React Native', 'GraphQL', 'Stripe', 'Redis'],
    features: [
      'Dynamic QR gate pass with biometric supervisor validation',
      'Real-time mess meal attendance and calorie calculator',
      'Hostel room maintenance ticketing with photo uploads',
      'Peer-to-peer laundry room queue management',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=60',
    ],
    packageSize: '21.0 MB',
    minAndroid: 'Android 8.1 (API 27)',
    status: 'published',
    updatedAt: '2026-08-20T11:45:00.000Z',
    githubUrl: 'https://github.com/example/hostelease',
    demoUrl: 'https://hostelease.example.com',
  },
  {
    id: 'app-005',
    name: 'FinTrack Pro',
    slug: 'fintrack-pro',
    icon: '📊',
    shortDescription: 'Zero-knowledge personal budget tracker and crypto portfolio manager.',
    description:
      'FinTrack Pro delivers private, client-side encrypted financial tracking with automated SMS expense parsing, mutual fund synchronization, and dividend projection models.',
    version: '2.0.0',
    category: 'Finance',
    developer: 'Apex Ledger',
    developerVerified: true,
    rating: 4.9,
    ratingCount: 2800,
    downloads: 87000,
    technologies: ['Kotlin', 'SQLCipher', 'Charts.js', 'Biometrics API'],
    features: [
      'Zero-knowledge on-device AES-256 encryption',
      'Automated transaction parsing from bank alerts',
      'Portfolio asset allocation rebalancing alerts',
      'Multi-currency support with live forex updates',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=60',
    ],
    packageSize: '16.5 MB',
    minAndroid: 'Android 10.0 (API 29)',
    status: 'published',
    updatedAt: '2026-09-04T16:20:00.000Z',
    githubUrl: 'https://github.com/example/fintrack',
    demoUrl: 'https://fintrack.example.com',
  },
  {
    id: 'app-006',
    name: 'NeuralSketch AI',
    slug: 'neural-sketch-ai',
    icon: '✨',
    shortDescription: 'On-device generative art canvas and vector illustrator.',
    description:
      'NeuralSketch AI enables concept artists and illustrators to generate raster-to-vector artwork, convert rough doodles into high-resolution illustrations, and export SVG layers directly.',
    version: '1.1.0',
    category: 'AI',
    developer: 'Synthetix Media',
    developerVerified: true,
    rating: 4.8,
    ratingCount: 1670,
    downloads: 53400,
    technologies: ['C++', 'ONNX Runtime', 'OpenGL ES 3.0', 'Kotlin'],
    features: [
      'NPU-accelerated neural diffusion running 100% on-device',
      'Stylus pressure sensitivity with tilt response',
      'Infinite canvas with non-destructive layers',
      'Export to SVG, PDF, and high-DPI PNG formats',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=800&auto=format&fit=crop&q=60',
    ],
    packageSize: '45.2 MB',
    minAndroid: 'Android 11.0 (API 30)',
    status: 'published',
    updatedAt: '2026-09-05T19:10:00.000Z',
    githubUrl: 'https://github.com/example/neuralsketch',
    demoUrl: 'https://neuralsketch.example.com',
  },
];

export const mockCategories = [
  {
    name: 'Education',
    count: 142,
    icon: 'GraduationCap',
    description: 'Learning portals, tutoring apps, language tools, and study planners.',
    color: 'from-blue-500/20 to-indigo-500/20',
  },
  {
    name: 'Productivity',
    count: 289,
    icon: 'Briefcase',
    description: 'Task managers, time trackers, note taking, and collaboration suites.',
    color: 'from-purple-500/20 to-pink-500/20',
  },
  {
    name: 'Health',
    count: 98,
    icon: 'HeartPulse',
    description: 'Fitness trackers, medical diagnostics, meditation, and nutrition.',
    color: 'from-rose-500/20 to-red-500/20',
  },
  {
    name: 'Finance',
    count: 114,
    icon: 'TrendingUp',
    description: 'Budgeting tools, crypto wallets, expense managers, and tax calculators.',
    color: 'from-emerald-500/20 to-teal-500/20',
  },
  {
    name: 'Utilities',
    count: 320,
    icon: 'Wrench',
    description: 'System tools, IoT controllers, file explorers, and sensor diagnostics.',
    color: 'from-amber-500/20 to-orange-500/20',
  },
  {
    name: 'AI',
    count: 76,
    icon: 'Sparkles',
    description: 'Neural generation, speech synthesis, vision processing, and automation.',
    color: 'from-cyan-500/20 to-blue-500/20',
  },
];

export const mockDeveloperMetrics = {
  totalApps: 8,
  publishedApps: 6,
  pendingApps: 2,
  totalDownloads: 148900,
  currentPlan: 'Gold Tier ($29/mo)',
  allotment: { used: 8, total: 10 },
  recentActivity: [
    { id: 1, action: 'Version 2.1.0 published for PulseGuard', time: '2 hours ago', type: 'publish' },
    { id: 2, action: 'Submission under review for SmartWater v1.4.3', time: '1 day ago', type: 'review' },
    { id: 3, action: 'New monthly record: 10,000 downloads passed', time: '3 days ago', type: 'milestone' },
    { id: 4, action: 'Gold tier subscription renewed successfully', time: '1 week ago', type: 'billing' },
  ],
};

export const mockAdminMetrics = {
  totalUsers: 245000,
  totalDevelopers: 3420,
  totalApplications: 1280,
  pendingApplications: 14,
  totalDownloads: 1890000,
  platformRevenue: '$84,250',
  recentSubmissions: [
    { id: 'sub-1', appName: 'AeroNav Flight Ops', developer: 'Aviation Corp', version: '1.0.4', date: '10 mins ago', status: 'pending' },
    { id: 'sub-2', appName: 'FarmPulse Crop IoT', developer: 'AgriTech India', version: '2.2.0', date: '1 hour ago', status: 'pending' },
    { id: 'sub-3', appName: 'SoundWave Studio', developer: 'AudioBit Labs', version: '3.0.0', date: '3 hours ago', status: 'pending' },
    { id: 'sub-4', appName: 'PulseGuard v2.1.0', developer: 'AuraHealth Labs', version: '2.1.0', date: '1 day ago', status: 'published' },
  ],
};
